---
- name: Installing boto in Controller Machine
  hosts: localhost
  become: true
  tasks:
    - name: Installing pip
      easy_install:
        name: pip
        state: present

    - name: Installing Boto
      pip:
        name: boto
        state: present

